// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sjfmmisrgzyqrubnijpi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqZm1taXNyZ3p5cXJ1Ym5panBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwODA0MzAsImV4cCI6MjA2NDY1NjQzMH0.iWvGC9-aynEGZrIudEoAGeSma19Hp8GnH1nix30WOho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);